### ISSUE TITLE
When I use your jobs.js,EZ window feedback message:Failed to Fetch Module 00000204f9594460:65541, I don't know how to solve it. so please help me

### ISSUE THREAD

**Issue by A-Smiley** [Weissnix4711/ElementZero-scripts#2]

**Comment by A-Smiley** [comment]
I would appreciate it if you could help me

**Comment by A-Smiley** [comment]
I would appreciate it if you can help me

**Comment by Weissnix4711** [comment]
Make sure to enable economy and chatAPI in `custom.yaml`.

Also, what version of ElementZero are you using? The scripts work fine on 200626.

**Comment by A-Smiley** [comment]
> Make sure to enable economy and chatAPI in `custom.yaml`.
> 
> Also, what version of ElementZero are you using? The scripts work fine on 200626.

Thanks for your help, now it is running normally.

**Comment by Weissnix4711** [comment]
No problem.
